package co.sis.crirowil.persistencia;

public enum Categoria {

	ENTERO, REAL, CADENA_CARACTERES, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_ASIGNACION, DESCONOCIDO,OPERADOR_LOGICO, SEPARADOR, FIN_SENTENCIA, PARENTESIS_ABRE, PARENTESIS_CIERRA, LLAVES_ABRE, LLAVES_CIERRA
	
}
